# Generated by Django 4.0.6 on 2022-07-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=200)),
                ('author', models.CharField(choices=[('Unknown', 'Unknown'), ('Arun', 'Arun'), ('Mari', 'Mari'), ('Pranish', 'Pranish'), ('Naren', 'Naren'), ('Kavin', 'Kavin')], default='Unknown', max_length=50)),
                ('post_regarding', models.CharField(choices=[('Python', 'Python'), ('CSS', 'CSS'), ('HTML', 'HTML'), ('AJAX', 'AJAX'), ('Others', 'Others')], default='Python', max_length=15)),
                ('contact', models.PositiveIntegerField(default='0000000000')),
                ('brief_about_post', models.CharField(default='Nothing defined!!!', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
            ],
        ),
    ]
